// Worker entry (wrangler.jsonc "main"). Wraps the OpenNext handler generated in .open-next/ with the edge
// rules in lib/edge.ts (Cloudflare review of 2026-09-27, plan U1/U3/U4/U5).
// Keep this file tiny: it runs on every request and counts against the Workers Free CPU limit.

// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent until the first build.
import { default as handler } from "./.open-next/worker.js";
import { canonicalRedirect, htmlCacheControl, SECURITY_HEADERS } from "./lib/edge";

interface EdgeEnv {
  /** Set to "1" in .dev.vars only: local preview presents requests as http://unlimitinsure.com. */
  DISABLE_CANONICAL_REDIRECT?: string;
}

export default {
  async fetch(request: Request, env: EdgeEnv, ctx: ExecutionContext): Promise<Response> {
    if (env.DISABLE_CANONICAL_REDIRECT !== "1") {
      const to = canonicalRedirect(new URL(request.url));
      if (to) return Response.redirect(to, 301);
    }

    const res: Response = await handler.fetch(request, env, ctx);
    const out = new Response(res.body, res);
    for (const [k, v] of Object.entries(SECURITY_HEADERS)) out.headers.set(k, v);
    const cc = htmlCacheControl(out.headers.get("content-type"), out.headers.get("cache-control"));
    if (cc) out.headers.set("Cache-Control", cc);
    return out;
  },
};
