import { B, FIX, ADMIN_USER, ADMIN_PASS, launch } from "./_env.mjs";
const b = await launch();
const p = await (await b.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
const errs = []; p.on("pageerror", (e) => errs.push(e.message));
const step = (m) => console.log("✓", m);
await p.goto(B + "/admin/login");
await p.getByLabel("ชื่อผู้ใช้").fill(ADMIN_USER); await p.getByLabel("รหัสผ่าน").fill(ADMIN_PASS);
await p.getByRole("button", { name: "เข้าสู่ระบบ" }).click(); await p.waitForURL(/\/admin$/);
await p.goto(B + "/admin/import");
const tpl = await fetch(B + "/templates/unlimit-product-import.xlsx"); step("template download HTTP " + tpl.status + " " + tpl.headers.get("content-type"));
const upload = async (f) => { await p.locator('input[type=file]').setInputFiles(f); };
await upload(new URL("../../docs/examples/product-import-example.xlsx", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));
await p.getByText("product-import-example.xlsx").waitFor({ timeout: 30000 });
const counts = await p.locator("dl dd").allInnerTexts(); step("example preview counts " + counts.join("/"));
await p.getByRole("button", { name: "นำเข้าเป็นฉบับร่าง" }).click();
await p.getByText("นำเข้าแล้ว").waitFor(); step("example import: " + (await p.locator("section[role=status] ul").innerText()).replace(/\n/g, " | "));
await upload(FIX + "import-bad.xlsx");
await p.getByText("import-bad.xlsx").waitFor({ timeout: 30000 });
step("bad file errors: " + (await p.locator("section", { hasText: "ข้อผิดพลาด (" }).locator("tbody tr").count()) + ", import button shown: " + (await p.getByRole("button", { name: "นำเข้าเป็นฉบับร่าง" }).count()));
await upload(FIX + "import-good.xlsx");
await p.getByText("import-good.xlsx").waitFor({ timeout: 30000 });
await p.getByRole("button", { name: "นำเข้าเป็นฉบับร่าง" }).click();
await p.getByText("นำเข้าแล้ว").waitFor(); step("new version import: " + (await p.locator("section[role=status] ul").innerText()).replace(/\n/g, " | "));
await p.goto(B + "/admin/products/a-type1-dealer");
step("product versions: " + (await p.locator("h2", { hasText: "เวอร์ชัน" }).allInnerTexts()).join(", "));
step("v3 status badges: " + (await p.locator("section", { hasText: "เวอร์ชัน 3" }).first().locator("span.rounded-full").allInnerTexts()).slice(0, 2).join(", "));
console.log(errs.length ? "PAGE ERRORS:\n" + errs.join("\n") : "no page errors");
await b.close();
