import { B, FIX, ADMIN_USER, ADMIN_PASS, launch } from "./_env.mjs";
const b = await launch();
const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage();
const errs = []; p.on("pageerror", (e) => errs.push(e.message));
const step = (m) => console.log("✓", m);
await p.goto(B + "/");
await p.getByRole("button", { name: /เช็กราคาเลย/ }).click();
await p.waitForURL(/step=use/); step("hero → usage step");
await p.getByText("รถครอบครัว").click();
await p.getByRole("button", { name: "ถัดไป" }).click();
await p.waitForURL(/step=needs/);
const checked = await p.locator('input[name="priorities"]:checked').count(); step(`needs step, ${checked} priorities preselected from usage`);
await p.getByText("ไม่มีค่าเสียหายส่วนแรก").first().click();
await p.getByRole("button", { name: /ดูแพ็กเกจ/ }).click();
await p.waitForURL(/quote\/results/); step("results: " + (await p.locator("article").count()) + " cards");
await p.getByRole("button", { name: "เปรียบเทียบ", exact: true }).nth(0).click();
await p.getByRole("button", { name: "เปรียบเทียบ", exact: true }).nth(0).click();
await p.getByRole("region", { name: /เลือกเปรียบเทียบ/ }).getByRole("button", { name: /เปรียบเทียบ/ }).click();
await p.waitForURL(/compare/); step("compare: " + (await p.locator("thead th").count() - 1) + " plans; summary: " + (await p.locator("#diff-title").count()));
await p.getByRole("button", { name: /อธิบาย ค่าเสียหายส่วนแรก/ }).first().click();
const dlg = p.locator("dialog[open]"); await dlg.waitFor(); step("explain dialog: " + (await dlg.locator("h2").innerText()));
await p.keyboard.press("Escape"); await dlg.waitFor({ state: "detached" }).catch(() => {});
await p.getByRole("link", { name: "เลือกแผนนี้" }).first().click();
await p.waitForURL(/\/(buy\/|advisor)/); step("select plan → " + new URL(p.url()).pathname);
await p.goBack(); await p.waitForURL(/compare/);
await p.getByRole("link", { name: /ปรึกษา/ }).last().click();
await p.waitForURL(/advisor/);
await p.getByRole("button", { name: /ขอให้ที่ปรึกษา/ }).click();
step("advisor validation errors: " + (await p.locator("[aria-invalid=true]").count()));
await p.waitForTimeout(500); const ctxText = await p.locator("main").innerText(); step("context shows compared: " + ctxText.includes("เปรียบเทียบแล้ว"));
await p.getByLabel("ชื่อที่ให้เรียก").fill("ทดสอบ");
await p.getByLabel("เบอร์โทรศัพท์").fill("0812345678");
await p.getByText(/ยินยอมให้ Unlimit/).click();
await p.getByRole("button", { name: /ขอให้ที่ปรึกษา/ }).click();
await p.getByText("ได้รับคำขอแล้ว").waitFor(); step("lead submitted");
console.log(errs.length ? "PAGE ERRORS:\n" + errs.join("\n") : "no page errors");
await b.close();
