// Collects every `verify` item from content/* into docs/verify-before-launch.md.
// Usage: npm run content:verify
import { writeFileSync } from "node:fs";
import { claimsCopy } from "@/content/claims";
import { faq } from "@/content/faq";
import { glossary } from "@/content/glossary";
import { homeCopy } from "@/content/home";
import { purchaseCopy } from "@/content/purchase";
import { labArticles } from "@/content/lab";
import { privacyPolicy, termsOfUse } from "@/content/legal";
import { scenarioCopy } from "@/content/scenarios";

type Group = { title: string; source: string; items: { where: string; text: string }[] };

const groups: Group[] = [
  { title: "Homepage business claims", source: "content/home.ts", items: (homeCopy.verify ?? []).map((t) => ({ where: "home", text: t })) },
  { title: "Privacy policy", source: "content/legal.ts", items: privacyPolicy.verify.map((t) => ({ where: "privacy", text: t })) },
  { title: "Terms of use", source: "content/legal.ts", items: termsOfUse.verify.map((t) => ({ where: "terms", text: t })) },
  {
    title: "Glossary (Explain dialogs)",
    source: "content/glossary.ts",
    items: Object.entries(glossary).flatMap(([k, e]) => (e.verify ?? []).map((t) => ({ where: `${k} (${e.term})`, text: t }))),
  },
  {
    title: "Coverage simulator",
    source: "content/scenarios.ts",
    items: Object.entries(scenarioCopy).flatMap(([k, s]) => (s.verify ?? []).map((t) => ({ where: `${k} (${s.label})`, text: t }))),
  },
  { title: "Insurance Lab", source: "content/lab.ts", items: labArticles.flatMap((a) => (a.verify ?? []).map((t) => ({ where: a.slug, text: t }))) },
  { title: "FAQ", source: "content/faq.ts", items: faq.flatMap((f) => (f.verify ?? []).map((t) => ({ where: f.question, text: t }))) },
  {
    title: "Claims guidance",
    source: "content/claims.ts",
    items: [
      ...claimsCopy.guides.flatMap((g) => g.verify.map((t) => ({ where: g.title, text: t }))),
      ...claimsCopy.faq.flatMap((f) => (f.verify ?? []).map((t) => ({ where: f.question, text: t }))),
    ],
  },
  { title: "Purchase and tracking", source: "content/purchase.ts", items: purchaseCopy.verify.map((t) => ({ where: "buy / track", text: t })) },
];

const total = groups.reduce((n, g) => n + g.items.length, 0);
const lines = [
  "# Verify Before Launch",
  "",
  `Generated by \`npm run content:verify\` from the \`verify\` fields in \`content/*\`. Do not edit by hand. ${total} items.`,
  "",
  "A licensed person (and a lawyer / DPO for the legal pages) confirms each item, then the content owner updates the copy and removes the item from its `verify` array.",
  "",
  "Also outside content: broker licence number (trust strip, footer, terms); authorised insurer list and logo permission; Unlimit's after-sales and claims support scope.",
  "",
];
for (const g of groups) {
  if (g.items.length === 0) continue;
  lines.push(`## ${g.title} (${g.items.length})`, `_Source: \`${g.source}\`_`, "");
  for (const i of g.items) lines.push(`- [ ] **${i.where}** — ${i.text}`);
  lines.push("");
}
writeFileSync("docs/verify-before-launch.md", lines.join("\n"));
console.log(`docs/verify-before-launch.md: ${total} items`);
