// Generates seed/mock-catalog.sql from lib/data (the MOCK catalogue) for `wrangler d1 execute`.
// Usage: npm run db:seed:build
import { writeFileSync } from "node:fs";
import { mockCatalog } from "@/lib/data";
import { seedCatalog } from "@/lib/db/catalog";
import { createTestDb } from "@/lib/db/testing";

const tables = ["insurers", "vehicle_brands", "vehicle_models", "products", "product_versions"];

function literal(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  const { db, raw } = createTestDb();
  await seedCatalog(db, mockCatalog);
  const lines = [
    "-- MOCK catalogue for the prototype. Generated by scripts/build-seed.ts; do not edit by hand.",
    "-- Deletes and re-inserts catalogue tables only. Leads are untouched.",
    ...[...tables].reverse().map((t) => `DELETE FROM ${t};`),
  ];
  for (const t of tables) {
    const rows = raw.prepare(`SELECT * FROM ${t}`).all() as Record<string, unknown>[];
    for (const r of rows) {
      const cols = Object.keys(r);
      lines.push(`INSERT INTO ${t} (${cols.join(", ")}) VALUES (${cols.map((c) => literal(r[c])).join(", ")});`);
    }
  }
  writeFileSync("seed/mock-catalog.sql", lines.join("\n") + "\n");
  console.log(`seed/mock-catalog.sql: ${lines.length} statements`);
}

main();
